using System.Collections.Generic;
using UnityEngine;

public class Spawner : MonoBehaviour
{
    [SerializeField] private GameObject prefab; // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½iPrefabï¿½j
    [SerializeField] private int MinNum = 3;    // ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ÌÅï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    [SerializeField] private int MaxNum = 30;   // ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ÌÅ‘å¶ï¿½ï¿½ï¿½ï¿½

    [SerializeField] private int MinValue = 300;     // ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½Ìï¿½ï¿½ï¿½ï¿½Åï¿½ï¿½Æ‚È‚ï¿½Æ‚ï¿½ï¿½ÌƒZï¿½ï¿½ï¿½Tï¿½[ï¿½ï¿½ï¿½ï¿½l
    [SerializeField] private int MaxValue = 2000;    // ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½Ìï¿½ï¿½ï¿½ï¿½Å‘ï¿½Æ‚È‚ï¿½Æ‚ï¿½ï¿½ÌƒZï¿½ï¿½ï¿½Tï¿½[ï¿½ï¿½ï¿½ï¿½l
    public int nowNum = 0;                      // ï¿½ï¿½ï¿½İ‚ÌƒIï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½Ìİ’è”

    private List<GameObject> objects = new List<GameObject>();  // ï¿½Ç—ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½Ìƒï¿½ï¿½Xï¿½g
    private bool isSpawnable => objects.Count < MaxNum; // ï¿½ï¿½ï¿½ï¿½ï¿½Â”\ï¿½ï¿½ï¿½Ìƒtï¿½ï¿½ï¿½O

    public int Num => objects.Count;    // ï¿½ï¿½ï¿½İŠÇ—ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½Ìï¿½

    private void Start()
    {
        if (MinNum > 0) Add(MinNum);
    }

    private void Update()
    {
        // ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½Ìİ’è”ï¿½ÆŠÇ—ï¿½ï¿½ï¿½ï¿½Éï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ê‡ï¿½Aï¿½ï¿½ï¿½Ì•ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½Ç‰ï¿½ï¿½Eï¿½íœï¿½ï¿½ï¿½ï¿½
        if( nowNum < Num ) {
            Sub(Num - nowNum);
        }
        else if(nowNum > Num)
        {
            Add(nowNum - Num);
        }
    }

    // ï¿½Zï¿½ï¿½ï¿½Tï¿½[ï¿½ÌŒÂï¿½ï¿½ï¿½ï¿½Zï¿½ï¿½ï¿½Tï¿½[ï¿½ï¿½ñ‚©‚ï¿½Xï¿½Vï¿½ï¿½ï¿½ï¿½
    public void UpdateNowNum()
    {
        // ï¿½Zï¿½ï¿½ï¿½Tï¿½[ï¿½Ì‘ï¿½ï¿½ï¿½lï¿½ï¿½ï¿½æ“¾
        SensorDataManager sdm = SensorDataManager.Instance;
        if (sdm == null || sdm.GetSensorData("co2") == null)
        {
            return;
        }
        float nowValue = sdm.GetSensorData("co2").Stat.Latest;
        // ï¿½ï¿½ï¿½İ‚ÌŒÂï¿½ï¿½ï¿½ï¿½vï¿½Z
        nowNum = (int)Mathf.Round(MinNum + (float)(MaxNum - MinNum) * (nowValue - MinValue) / (MaxValue - MinValue));
    }

    // ï¿½ï¿½ï¿½ï¿½ï¿½wï¿½è‚µï¿½ÄAï¿½ï¿½ï¿½Ì•ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ğ‘‚â‚·
    private void Add(int n = 1)
    {
        if (n <= 0 || Num >= MaxNum) return;
        else if (n + Num >= MaxNum) n = MaxNum - Num;
        for(int i = 0; i < n; i++)
        {
            CreateObject();
        }
    }
    // ï¿½ï¿½ï¿½ï¿½ï¿½wï¿½è‚µï¿½ÄAï¿½ï¿½ï¿½Ì•ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½ï¿½ï¿½ï¿½ç‚·
    private void Sub(int n = 0)
    {
        if (n <= 0) return;
        else if (Num - n < MinNum) n = Num - MinNum;

        if (n > Num) n = Num;
        for(int i = 0; i < n; i++)
        {
            DestroyObject(objects[0]);
        }
    }


    // ï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ğ¶‚İoï¿½ï¿½
    private void CreateObject()
    {
        if (isSpawnable)
        {
            // ï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ğ¶‚İoï¿½ï¿½
            GameObject newObject = Instantiate(prefab, transform.position, Quaternion.identity, transform.parent);
            objects.Add(newObject);
        }
    }

    // ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    private void DestroyObject(GameObject targetObject)
    {
        if(objects.Contains(targetObject))
        {
            objects.Remove(targetObject);
            Destroy(targetObject);
        }
    }
}
